version: '2.2'

services:
    tm-default:
        privileged: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PYTHONUNBUFFERED=1
            - CANEMRA_INDEX=${CAMERA_INDEX}
            - SCENARIO_NAME=homecare
        volumes:
            - ./tm:/workspace/src/tm
            - ./modules/PM/dummy_tm:/workspace/src/dummy_tm
            - ./modules/DM_Generator/dm_generator:/workspace/src/dm_generator
            - ./modules/DM_Intent/dm_intent:/workspace/src/dm_intent
            - ./modules/KM/km:/workspace/src/km
            - ./modules/Vision/vision:/workspace/src/vision
            - ./modules/Speech/speech:/workspace/src/speech
            - /etc/localtime:/etc/localtime

    tm-linux:
        extends:
            service: tm-default
        network_mode: host
