version: '2.2'

services:
    tm-default:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PYTHONUNBUFFERED=1
            - DM_NODE=homecare
        volumes:
            - ./src:/workspace/src/tm/src
            - ./modules/DM_Generator/src:/workspace/src/dm_generator/src
            - ./modules/KM/src:/workspace/src/km/src
            - ./modules/Vision/src:/workspace/src/vision/src
            - ./modules/Speech/src:/workspace/src/speech/src

    tm-linux:
        extends:
            service: tm-default
        network_mode: host

    tm-linux-test:
        extends:
            service: tm-linux
        devices:
            - /dev/video0:/dev/video0
            - /dev/snd:/dev/snd
