version: '2.2'

services:
    tm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: container
        network_mode: host
        environment:
            - DISPLAY=:0
        volumes:
            - ./src:/workspace/src/tm/src
            - ./modules/DM_Generator/src:/workspace/src/dm_generator/src
            - /tmp/.X11-unix:/tmp/.X11-unix
