version: '2.2'

services:
    tm-default:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PYTHONUNBUFFERED=1
            - scenario_name=homecare
        volumes:
            - ./tm:/workspace/src/tm
            - ./modules/DM_Generator/dm_generator:/workspace/src/dm_generator
            - ./modules/KM/km:/workspace/src/km
            - ./modules/Vision/vision:/workspace/src/vision
            - ./modules/Speech/speech:/workspace/src/speech
            - /etc/localtime:/etc/localtime

    tm-linux:
        extends:
            service: tm-default
        network_mode: host

    tm-linux-test:
        extends:
            service: tm-linux
        devices:
            - /dev/video0:/dev/video0
            - /dev/snd:/dev/snd
